// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckyumopnadbkekftzxyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXVtb3BuYWRia2VrZnR6eHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4OTAyMTgsImV4cCI6MjEwMTQ2NjIxOH0.Rx_VBo7r2wTvDcHVcuoi_2S5nF4GMDEmzHoJa_e0xb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});