// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { rememberAwareStorage } from '@/lib/remember-me';

const SUPABASE_URL = "https://ckyumopnadbkekftzxyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXVtb3BuYWRia2VrZnR6eHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4OTAyMTgsImV4cCI6MjEwMTQ2NjIxOH0.Rx_VBo7r2wTvDcHVcuoi_2S5nF4GMDEmzHoJa_e0xb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Đổi từ localStorage cố định sang adapter tùy theo lựa chọn "Ghi nhớ đăng nhập" của người dùng
    // (xem src/lib/remember-me.ts). Nếu Lovable tự sinh lại file này, dòng "storage:" cần đổi lại
    // đúng như dưới đây để không mất tính năng.
    storage: typeof window !== 'undefined' ? rememberAwareStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});